/**
 * `aigc_creative_to_video` — end-to-end tool that takes a Chinese
 * markdown script and renders every shot into a Hailuo-2.3 video,
 * with rule-based camera-move assignment for each shot.
 *
 * No LLM is invoked: the script is assumed to be supplied by the user
 * (e.g. generated by an external tool or pasted from a writer). This
 * is intentional given that MiniMax LLM endpoints are not bundled with
 * the same token-bucket as video generation on the subscription tier.
 *
 * Run:  node bin/creative-to-video.mjs path/to/script.md
 */

import { defineTool } from '@deepseek-ai/dsh-tools';

import { CreativePipeline } from '../workflow/creative_pipeline.js';
import { parseScript } from '../workflow/script_parser.js';
import { decomposeIntoShots } from '../workflow/shot_decomposer.js';
import { buildHailuoPrompt } from '../workflow/prompt_builder.js';

import { loadConfig, getProviderConfig } from '../providers/config.js';
import { createVideoProvider } from '../providers/video/index.js';

export const creativeToVideoTool = defineTool({
  name: 'aigc_creative_to_video',
  description:
    'Render every shot of a Chinese markdown script into a Hailuo-2.3 video. ' +
    'Each stage direction becomes one shot with rule-based camera moves; ' +
    'each shot is submitted to MiniMax-Hailuo-2.3 and downloaded to disk. ' +
    '**Consumes Hailuo quota** (1 token per shot).',
  parameters: {
    script_markdown: {
      type: 'string',
      required: true,
      description:
        'Full markdown script (same format as the user-supplied 狐狸 example): title, metadata, then acts with (stage directions) and **character**: dialog lines.',
    },
    max_shots: {
      type: 'integer',
      description: 'Cap the number of shots to render (default 12, hard cap 30).',
    },
    project_name: {
      type: 'string',
      description: 'Project identifier (used for subdirectory naming).',
    },
    output_dir: {
      type: 'string',
      description: 'Override the default output directory (code/result/creative).',
    },
    dry_run: {
      type: 'boolean',
      description:
        'If true, parse + decompose + build prompts only; do not submit to Hailuo. ' +
        'Useful for inspection.',
    },
    references: {
      type: 'array',
      items: { type: 'string' },
      description:
        'Optional reference image URLs (data URLs or http(s) URLs) for subject ' +
        'consistency. First entry is used as `first_frame` for every shot; all ' +
        'entries are passed as `reference_image` so Hailuo v2 keeps the subject ' +
        'consistent across the final cut. Convert local paths to data URLs via ' +
        '`src/util/image_to_dataurl.ts` before passing them in.',
    },
  },
  output: {
    schema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        script: {
          type: 'object',
          additionalProperties: false,
          properties: {
            title: { type: 'string' },
            characters: { type: 'array', items: { type: 'string' } },
            acts: { type: 'integer' },
          },
        },
        shots_total: { type: 'integer' },
        shots_succeeded: { type: 'integer' },
        shots_failed: { type: 'integer' },
        shots: {
          type: 'array',
          items: {
            type: 'object',
            additionalProperties: false,
            properties: {
              shot_index: { type: 'integer' },
              act: { type: 'integer' },
              description: { type: 'string' },
              camera_move: { type: 'string' },
              duration: { type: 'integer' },
              characters: { type: 'array', items: { type: 'string' } },
              prompt: { type: 'string' },
              video_url: { type: 'string' },
              video_path: { type: 'string' },
              error: { type: 'string' },
            },
          },
        },
      },
    },
    render: (_args, value) => [
      { type: 'text', text: `[aigc_creative_to_video]\n${JSON.stringify(value, null, 2)}` },
    ],
  },
  async execute(args, exec) {
    // Dry-run: parse + decompose + build prompts only.
    if (args.dry_run) {
      const parsed = parseScript(args.script_markdown);
      const shots = decomposeIntoShots(parsed, { maxShots: args.max_shots ?? 12 });
      const prompts = shots.map((s) => buildHailuoPrompt(s, parsed));
      return {
        script: { title: parsed.title, characters: parsed.characters.map((c) => c.name), acts: parsed.acts.length },
        shots_total: shots.length,
        shots_succeeded: 0,
        shots_failed: 0,
        shots: shots.map((s, i) => ({
          shot_index: s.index,
          act: s.act,
          description: s.description,
          camera_move: s.camera_move,
          duration: s.duration,
          characters: s.characters,
          prompt: prompts[i]?.prompt ?? '',
          video_url: '',
          video_path: '',
        })),
      };
    }

    const cfg = loadConfig('config.yaml');
    const videoAlias = cfg.pipeline.videoProvider;
    const videoCfg = getProviderConfig(cfg, videoAlias);
    if (!videoCfg) {
      throw new Error(`video provider '${videoAlias}' not configured in config.yaml`);
    }
    const video = createVideoProvider(videoAlias, videoCfg);
    const pipeline = new CreativePipeline(video);

    return await pipeline.run(
      {
        script_markdown: args.script_markdown,
        max_shots: args.max_shots,
        project_name: args.project_name,
        output_dir: args.output_dir,
        ...(args.references && args.references.length > 0 ? { references: args.references } : {}),
      },
      exec.signal
    );
  },
});
